version: 2.1


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
              cd frontend
              npm install
              npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
 

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
              cd backend
              npm install
              npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build


  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end test
          command: |
              cd frontend
              npm install
              npm run test
    
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end test
          command: |
              cd backend
              npm install
              npm run test


  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run: 
          name: Analyze Front-end
          command: |
              cd frontend
              npm install
              npm audit fix --audit-level=critical --force
              npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
           name: Analyze Back-end
           command: |
              cd backend
              npm install
              npm update passport-oauth2 --depth 3
              npm update path-parse --depth 13 
              npm update hosted-git-info --depth 16
              npm update color-string --depth 6
              npm update typeorm --depth 1
              npm update ajv --depth 3
              npm update kind-of --depth 23
              npm update ini --depth 7
              npm update dot-prop --depth 4
              npm update terser-webpack-plugin --depth 2
              npm update conventional-changelog-conventionalcommits --depth 3
              npm update js-yaml --depth 2
              npm update elliptic --depth 5
              npm update ws --depth 10
              npm update lodash --depth 18
              npm update moment --depth 3 
              npm update ansi-regex --depth 8
              npm update async --depth 3
              npm update tmpl --depth 15
              npm update jsprim --depth 12
              npm update y18n --depth 10
              npm update cli-highlight --depth 2
              npm update node-fetch --depth 3
              npm update ssri --depth 4
              npm audit --audit-level=critical 

               
    

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]